name: Generate Snapshot Index

on:
  workflow_run:
    workflows: ["Update Cloud Permissions"]
    types:
      - completed

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate Index Files
        run: |
          python scripts/generate_snapshot_index.py

      - name: Commit and Push Index Files
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add snapshots/*_snapshots_index.json
          git commit -m "Update snapshot index files"
          git push
